//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agendamento()
        {
            this.Execucao = new HashSet<Execucao>();
            this.Agendamento_TestData = new HashSet<Agendamento_TestData>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> RotinaDiaria { get; set; }
        public Nullable<System.DateTime> InicioAgendamento { get; set; }
        public Nullable<System.DateTime> TerminoAgendamento { get; set; }
        public string Output { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Execucao> Execucao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento_TestData> Agendamento_TestData { get; set; }
    }
}
