//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbienteVirtual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmbienteVirtual()
        {
            this.Script_CondicaoScript_Ambiente = new HashSet<Script_CondicaoScript_Ambiente>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string IP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Script_CondicaoScript_Ambiente> Script_CondicaoScript_Ambiente { get; set; }
    }
}
