//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataPool()
        {
            this.TestData = new HashSet<TestData>();
        }
    
        public int Id { get; set; }
        public int IdTDM { get; set; }
        public int IdAut { get; set; }
        public Nullable<int> IdDemanda { get; set; }
        public int IdScript_CondicaoScript { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> QtdSolicitada { get; set; }
        public string Observacao { get; set; }
        public System.DateTime DataSolicitacao { get; set; }
        public Nullable<System.DateTime> DataInicioExecucao { get; set; }
        public Nullable<System.DateTime> DataTermino { get; set; }
    
        public virtual AUT AUT { get; set; }
        public virtual Demanda Demanda { get; set; }
        public virtual Script_CondicaoScript Script_CondicaoScript { get; set; }
        public virtual TDM TDM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestData> TestData { get; set; }
    }
}
