//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Execucao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Execucao()
        {
            this.TestData = new HashSet<TestData>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdScript_CondicaoScript_Ambiente { get; set; }
        public Nullable<int> IdTestData { get; set; }
        public int IdStatusExecucao { get; set; }
        public int IdTipoFaseTeste { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> SituacaoAmbiente { get; set; }
        public string ToscaInput { get; set; }
        public string ToscaOutput { get; set; }
    
        public virtual Script_CondicaoScript_Ambiente Script_CondicaoScript_Ambiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestData> TestData { get; set; }
        public virtual TipoFaseTeste TipoFaseTeste { get; set; }
        public virtual StatusExecucao StatusExecucao { get; set; }
    }
}
