//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdDataPool { get; set; }
        public Nullable<int> IdTestData { get; set; }
        public Nullable<int> IdExecucao { get; set; }
        public string Acao { get; set; }
        public string Valores { get; set; }
        public string Entidade { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
