//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapaCalor
    {
        public int Id { get; set; }
        public int IdTelaMapaCalor { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Data { get; set; }
        public int PosX { get; set; }
        public int PosY { get; set; }
        public string Resolucao { get; set; }
    
        public virtual TelaMapaCalor TelaMapaCalor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
