//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroValor_Historico
    {
        public int Id { get; set; }
        public int IdParametroValor { get; set; }
        public System.DateTime TempoInicio { get; set; }
        public System.DateTime TempoTermino { get; set; }
        public string Valor { get; set; }
    
        public virtual ParametroValor ParametroValor { get; set; }
    }
}
