//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroValor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParametroValor()
        {
            this.ParametroValor_Historico = new HashSet<ParametroValor_Historico>();
            this.ParametroValor1 = new HashSet<ParametroValor>();
        }
    
        public int Id { get; set; }
        public int IdTestData { get; set; }
        public int IdParametroScript { get; set; }
        public Nullable<int> IdParametroValor_Origem { get; set; }
        public string Valor { get; set; }
    
        public virtual ParametroScript ParametroScript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametroValor_Historico> ParametroValor_Historico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametroValor> ParametroValor1 { get; set; }
        public virtual ParametroValor ParametroValor2 { get; set; }
        public virtual TestData TestData { get; set; }
    }
}
