//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script_CondicaoScript
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Script_CondicaoScript()
        {
            this.DataPool = new HashSet<DataPool>();
            this.ParametroScript = new HashSet<ParametroScript>();
            this.Script_CondicaoScript_Ambiente = new HashSet<Script_CondicaoScript_Ambiente>();
            this.TestData = new HashSet<TestData>();
        }
    
        public int Id { get; set; }
        public int IdScript { get; set; }
        public Nullable<int> IdCondicaoScript { get; set; }
        public string QueryTosca { get; set; }
        public string ListaExecucaoTosca { get; set; }
        public string CaminhoArquivoTCS { get; set; }
        public string DiretorioRelatorio { get; set; }
        public System.DateTime TempoEstimadoExecucao { get; set; }
        public string NomeTecnicoScript { get; set; }
    
        public virtual CondicaoScript CondicaoScript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPool> DataPool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametroScript> ParametroScript { get; set; }
        public virtual Script Script { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Script_CondicaoScript_Ambiente> Script_CondicaoScript_Ambiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestData> TestData { get; set; }
    }
}
