//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Script()
        {
            this.Script_CondicaoScript = new HashSet<Script_CondicaoScript>();
            this.Script1 = new HashSet<Script>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdScriptPai { get; set; }
        public Nullable<int> IdAUT { get; set; }
        public string Descricao { get; set; }
    
        public virtual AUT AUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Script_CondicaoScript> Script_CondicaoScript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Script> Script1 { get; set; }
        public virtual Script Script2 { get; set; }
    }
}
