//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDM_Usuario
    {
        public int IdUsuario { get; set; }
        public int IdTDM { get; set; }
        public string Descricao { get; set; }
    
        public virtual TDM TDM { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
