//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaefazWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelaMapaCalor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelaMapaCalor()
        {
            this.MapaCalor = new HashSet<MapaCalor>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public byte[] Imagem { get; set; }
        public string Caminho { get; set; }
        public string Resolucao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapaCalor> MapaCalor { get; set; }
    }
}
