CREATE PROCEDURE [dbo].[PR_EXCLUIR_ANALISE]
	@IdAnalise int
AS
BEGIN

	UPDATE 
		PRODUTO 
	SET 
		IDPRODUTOPAI = NULL,
		IdProdContesPlaMovSai = NULL,
		IdProdContesPlaMovEnt = NULL,
		IdProdContesPlaFinal = NULL,
		IdProdContesPlaInicial = NULL
	WHERE 
		IDANALISE = @IDANALISE

	DELETE
		MOVIMENTACAO
	FROM 
		MOVIMENTACAO 
		INNER JOIN PRODUTO ON PRODUTO.ID = MOVIMENTACAO.IDPRODUTO
	WHERE 
		IDANALISE = @IDANALISE
	
	DELETE
		ESTOQUE
	FROM 
		ESTOQUE 
		INNER JOIN PRODUTO ON PRODUTO.ID = ESTOQUE.IDPRODUTO
	WHERE 
		IDANALISE = @IDANALISE
	
	DELETE FROM PRODUTO WHERE IDANALISE = @IDANALISE
  
	DELETE FROM ANALISE WHERE ID = @IDANALISE
END